version: "3.5"

services:

  nginx:
    build: nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../log/front:/var/log/nginx
      - phpsocket:/var/run
      - ../api:/www

  front:
    build: front/
    ports:
      - 8000:8080
    volumes:
      - ../front:/front

  back:
    build: back/
    ports:
      - 9000:9000
    volumes:
      - ../log/back:/usr/local/var/log
      - ./back/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsocket:/var/run
      - ../api:/www
#      - back/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../db:/var/lib/mysql
      - ../arh:/arh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD:password

volumes:
  phpsocket: